[package]
name = "chargrid-talk"
version = "0.1.0"
edition = "2021"

[dependencies]
chargrid_core = "0.1"
chargrid_runtime = "0.1"
chargrid_wgpu = "0.2"
grid_2d = "0.15"
direction = "0.18"
rand = "0.8"
rand_isaac = "0.3"
